version: '1.0'
name: tp0

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

services:
  server:
    container_name: server
    entrypoint: python /main.py
    environment:
      - PYTHONUNBUFFERED=1
    image: server:latest
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
    ports:
      - "12345:12345"

  client1:
    container_name: client1
    depends_on:
      - server
    build:
      context: .
      dockerfile: ./client/Dockerfile
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Santiago Lionel
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    image: client:latest
    networks:
      - testing_net
    volumes:
      - ./client/config.yaml:/config.yaml
